<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Linear Regression</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<p>In the <code>uwIntroStats</code> package, we have set out to make regression and analysis easier by:</p>

<ul>
<li>allowing the user to specify any type of regression from one function</li>
<li>allowing the user to specify multiple-partial F-tests</li>
<li>displaying output in a more intuitive fashion than base R</li>
</ul>

<p>This function is <code>regress()</code>. The basic arguments to this function, which unlock all of its potential, are</p>

<ul>
<li><code>fnctl</code> - the functional</li>
<li><code>formula</code> - the formula for the linear model</li>
<li><code>data</code> - the data to use for the model</li>
<li><code>id</code> - the identification variable in data with repeated measurements</li>
</ul>

<p>We use the concept of a <em>functional</em> to handle our first goal. A functional takes a function as its argument and returns a number - hence the mean is a functional, because it takes a distribution as its argument and returns a single number. The allowed functionals to <code>regress()</code> are</p>

<table><thead>
<tr>
<th>Functional</th>
<th align="left">Type of Regression</th>
<th align="left">Previous command (package)</th>
</tr>
</thead><tbody>
<tr>
<td><code>&quot;mean&quot;</code></td>
<td align="left">Linear Regression</td>
<td align="left"><code>lm()</code> (<code>stats</code> - base R)</td>
</tr>
<tr>
<td><code>&quot;geometric mean&quot;</code></td>
<td align="left">Linear Regression on logarithmically transformed Y</td>
<td align="left"><code>lm()</code>, with Y log transformed (<code>stats</code> - base R)</td>
</tr>
<tr>
<td><code>&quot;odds&quot;</code></td>
<td align="left">Logistic Regression</td>
<td align="left"><code>glm(family = binomial)</code> (<code>stats</code> - base R)</td>
</tr>
<tr>
<td><code>&quot;rate&quot;</code></td>
<td align="left">Poisson Regression</td>
<td align="left"><code>glm(family = poisson)</code> (<code>stats</code> - base R)</td>
</tr>
</tbody></table>

<p>The <em>formula</em> to <code>regress()</code> is the same as a formula given to <code>lm()</code> or any of the other regression commands from base R, <code>survival</code>, or <code>geepack</code>, but with one small addition. To address our second goal of allowing the user to specify multiple-partial F-tests, we have added a special function - <code>U()</code> - which can be added to the formula. The <code>U()</code> function is documented more fully in <a href="u_intro.html">&ldquo;User Specified Multiple-Partial F-tests in Regression&rdquo;</a>. </p>

<p>The <em>data</em> argument is exactly the same as that in <code>lm()</code> or any of the other regression commands.</p>

<p>Last, <em>id</em> allows the user to fit a generalized estimating equations (GEE) model while using the same syntax as any of the functionals to <code>regress()</code>. The GEE framework is a useful way to model correlated data, which often comes in the form of repeated measurements.</p>

<h1>Linear Regression</h1>

<p>As a first example, we run a linear regression analysis of atrophy on age and male, from the <code>mri</code> data. This dataset is included in the <code>uwIntroStats</code> package, and its documentation can be found on Scott Emerson&#39;s website <a href="http://www.emersonstatistics.com/datasets/mri.pdf">here</a>.</p>

<pre><code class="r">## Preparing our R session
library(uwIntroStats)
</code></pre>

<pre><code>## 
## Attaching package: &#39;uwIntroStats&#39;
</code></pre>

<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     tabulate
</code></pre>

<pre><code class="r">data(mri)
</code></pre>

<pre><code class="r">regress(&quot;mean&quot;, atrophy ~ age + male, data = mri)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ age + male, data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.765  -8.582  -0.356   7.344  52.100 
## 
## Coefficients:
##                  Estimate  Naive SE  Robust SE    95%L      95%H     
## [1] Intercept     -17.83     6.081     6.557       -30.70    -4.959  
## [2] age            0.6819   0.08129   0.08769       0.5097    0.8540 
## [3] male           5.964     0.8857    0.8845       4.227     7.700  
##                     F stat    df Pr(&gt;F)   
## [1] Intercept            7.40 1    0.0067 
## [2] age                 60.47 1  &lt; 0.00005
## [3] male                45.46 1  &lt; 0.00005
## 
## Residual standard error: 12 on 732 degrees of freedom
## Multiple R-squared:   0.14,  Adjusted R-squared:  0.1376 
## F-statistic: 52.18 on 2 and 732 DF,  p-value: &lt; 2.2e-16
</code></pre>

<p>This call automatically prints the coefficients table. First, notice that by default robust standard error estimates (calculated using the <code>sandwich</code> package) are returned, in addition to the naive estimates. The robust estimates are also used to perform the inference - thus the confidence intervals, statistics, and p-values use these estimates of the standard error.</p>

<p>If we did not use robust standard error estimates, then in the case of linear regression we would be assuming that all groups have the same variance. Then any inference we make could be on the fact that the variances are different, rather than just on the means - which is usually what we want in linear regression. </p>

<p>F-statistics are also displayed by default. This allows us to display multiple-partial F-tests within the coefficients table, and is more in line with teaching philosophy at the University of Washington.</p>

<p>All of the usual inferential statements apply to our output. Thus we would say:</p>

<blockquote>
<p>We analyzed the association between cerebral atrophy, age, and sex by running a linear regression of cerebral atrophy modeled as a continuous variable on age - modeled as a continuous variable - and sex - modeled as a binary variable. We allowed for unequal variances among groups by computing robust standard error estimates using the Huber-White procedure. We calculated 95% confidence intervals and p-values using these same robust standard error estimates. </p>

<p>Based on this linear regression analysis, we estimate that for each one year increase in age, the mean cerebral atrophy score increases by 0.682 units. Based on a 95% confidence interval, the data suggest that this estimate is not unreasonable if the true coefficient for age was in the interval from 0.509 to 0.854. We also estimate that males have an average cerebral atrophy score of 5.96 units higher than females. Based on a 95% confidence interval, the data suggest that this estimate is not unreasonable if the true coefficient for sex was in the interval from 4.227 to 7.700. </p>
</blockquote>

<p>However, in this case we did not adjust for multiple comparisons in calculating the individual p-values. If we wanted to make inferential claims using these, we would have to use a correction. We could also use a multiple-partial F-test to test both coefficients simultaneously.</p>

<h2>Regression on the Geometric Mean</h2>

<p>In normal linear regression, we are comparing the mean of the response variable across groups defined by the predictors. However, if we were to log transform the response, we would be comparing the geometric mean across groups. In <code>regress()</code>, we simply have to use the <code>&quot;geometric mean&quot;</code> functional.</p>

<h1>Generalized Linear Regression</h1>

<p>Using the same function, and the same syntax, we can also run generalized linear regression. For example, if we wanted to examine the odds of having diabetes between males and females, we would run a logistic regression.</p>

<pre><code class="r">regress(&quot;odds&quot;, diabetes ~ male, data = mri)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;odds&quot;, formula = diabetes ~ male, data = mri)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.5593  -0.5593  -0.3823  -0.3823   2.3034  
## 
## Coefficients:
## 
## Raw Model:
##                  Estimate  Naive SE  Robust SE       F stat    df
## [1] Intercept     -2.580     0.2034    0.2037           160.39 1 
## [2] male           0.8037    0.2519    0.2522            10.15 1 
##                  Pr(&gt;F)   
## [1] Intercept    &lt; 0.00005
## [2] male           0.0015 
## 
## Transformed Model:
##                  e(Est)    e(95%L)   e(95%H)         F stat    df
## [1] Intercept     0.07580   0.05082    0.1131           160.39 1 
## [2] male           2.234     1.361     3.665             10.15 1 
##                  Pr(&gt;F)   
## [1] Intercept    &lt; 0.00005
## [2] male           0.0015 
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 501.59  on 734  degrees of freedom
## Residual deviance: 490.82  on 733  degrees of freedom
## AIC: 494.82
## 
## Number of Fisher Scoring iterations: 5
</code></pre>

<p>In all of the generalized linear regression output (and in the output from regression on the geometric mean), by default we see two tables. The <code>Raw Model</code> table displays coefficients and standard errors for the model after we have transformed the response variable, but we have not transformed back. Recall that in most generalized linear regression cases, we need to back-transform our results to get them in the original units. This is due to using a link function to model the regression. If you want to suppress printing this table, set <code>suppress = TRUE</code>.</p>

<p>The <code>Transformed Model</code> table does the back-transform for you. It exponentiates all of the coefficients and the confidence intervals so that they are in the original units. </p>

<p>Proportional hazards regression is no longer supported.</p>

<h1>Accounting for Correlated Data</h1>

<p>A common way to account for correlated data - for example longitudinal data, where we have multiple measurements on the same subjects over time - is to use the Generalized Estimating Equations (GEE) framework. We chose to use this framework in our <code>regress()</code> function because it gives flexibility and uses common conventions. To make use of this functionality, as we mentioned above, you simply need to specify the <code>id</code> argument in <code>regress()</code>. </p>

<p>For an example, we turn to the <code>salary</code> data, again hosted at Scott Emerson&#39;s <a href="http://www.emersonstatistics.com/datasets/salary.txt">website</a>. More information can be found in the <a href="http://www.emersonstatistics.com/datasets/salary.doc">documentation</a>, but these data essentially deal with university level faculty. In 1995, a survey was run asking the faculty to recall their salaries from the past. Each faculty member had records dating either to their starting year at the university or 1976, whichever was more recent. Thus we have repeated measurements on these individuals, and the variable of interest (salary) is highly correlated across measurements. </p>

<p>One interesting question to ask of these data involves discrimination based on sex. We will not model these data in the most sophisticated way (we leave that to the enterprising reader), but we can regress salary on sex and year, and involve their interaction. </p>

<pre><code class="r">salary &lt;- read.table(&quot;http://www.emersonstatistics.com/datasets/salary.txt&quot;, header = TRUE, stringsAsFactors = FALSE)

## create an indicator variable
salary$female &lt;- ifelse(salary$sex == &quot;F&quot;, 1, 0)
</code></pre>

<p>Now that the data is read in, we can run the regression. First we run a regular linear regression which does not properly account for the correlated data, and then we run the GEE based regression.</p>

<pre><code class="r">## linear regression
regress(&quot;mean&quot;, salary ~ female*year, data = salary)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = salary ~ female * year, data = salary)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3727.9  -907.4  -230.0   719.2  7605.5 
## 
## Coefficients:
##                    Estimate  Naive SE  Robust SE    95%L      95%H     
## [1] Intercept       -17417     176.5     167.6       -17745    -17088  
## [2] female            4102     420.7     299.5         3515      4689  
## [3] year             255.5     2.021     2.005        251.6     259.5  
## [4] female:year     -57.88     4.757     3.541       -64.82    -50.94  
##                       F stat    df Pr(&gt;F)   
## [1] Intercept          10802.86 1  &lt; 0.00005
## [2] female               187.59 1  &lt; 0.00005
## [3] year               16235.87 1  &lt; 0.00005
## [4] female:year          267.10 1  &lt; 0.00005
## 
## Residual standard error: 1423 on 19788 degrees of freedom
## Multiple R-squared:  0.487,  Adjusted R-squared:  0.4869 
## F-statistic:  7166 on 3 and 19788 DF,  p-value: &lt; 2.2e-16
</code></pre>

<p>From this call to regress, we would think that we had 19792 unique data points, which is quite a lot of faculty to have at a university. If we compare to the results from the GEE based regression, we will see how far off we are.</p>

<pre><code class="r">## GEE
regress(&quot;mean&quot;, salary ~ female*year, id = id, data = salary)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = salary ~ female * year, data = salary, 
##     id = id)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3727.9   -907.4   -230.0    719.2   7605.5  
## 
## Coefficients:
##                    Estimate  Std Err   95%L         95%H         Wald     
## [1] Intercept       -17417     283.6    -17973       -16861        3771.66
## [2] female            4102     528.7      3065         5138          60.20
## [3] year             255.5     3.536     248.6        262.5        5222.05
## [4] female:year     -57.88     6.370    -70.36       -45.39          82.56
##                    df Pr(&gt;|W|) 
## [1] Intercept      1  &lt; 0.00005
## [2] female         1  &lt; 0.00005
## [3] year           1  &lt; 0.00005
## [4] female:year    1  &lt; 0.00005
## 
##  Estimated Scale Parameters: 
##             Estimate  Std.err
## (Intercept)  2024610 77997.57
## 
##  Correlation: Structure =  independence 
## 
##  Number of Clusters:  1597 
## 
##  Maximum Cluster Size:  20
</code></pre>

<p>Now <code>regress()</code> tells us that we only have 1597 faculty members, which is much more reasonable. Also, it tells us that the &ldquo;maximum cluster size&rdquo; - i.e. the largest number of observations on any one id - is 20. This makes sense due to the sampling scheme, where some faculty have been at the university for 20 years by the time the survey was taken. </p>

<p>While our estimates of the coefficients are the same between the two calls to <code>regress()</code>, it is our standard error estimates and inference which are drastically different. When we overestimate how many unique samples we have (in the naive linear regression), our standard error is much smaller than it should be, and thus we have much larger F statistics and smaller p-values. While in this case our inference would be the same, since the p-values are on the same order of magnitude in both cases, failing to account for the correlation in these data is still a mistake.</p>

<h1>Re-parameterizations of a Variable</h1>

<p>There are three special functions in <code>uwIntroStats</code> which allow us to re-parameterize variables:</p>

<ul>
<li><code>dummy</code> - create dummy variables</li>
<li><code>lspline</code> - create linear splines</li>
<li><code>polynomial</code> - create a polynomial</li>
</ul>

<p>Each of these three functions is used to great effect in <code>regress()</code>. Also, each will give a multiple-partial F-test of the entire variable. This allows you to determine if the variable should be included in the model, rather than having only the coefficient estimates.</p>

<p>For example, we can model race as dummy variables to examine the differences in the odds of having diabetes between races. This allows us to better make comparisons, because modeling as dummy variables essentially creates indicator variables against a reference group.</p>

<pre><code class="r">regress(&quot;odds&quot;, diabetes ~ dummy(race), data = mri)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;odds&quot;, formula = diabetes ~ dummy(race), data = mri)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.6165  -0.4539  -0.4539  -0.4539   2.3459  
## 
## Coefficients:
## 
## Raw Model:
##                    Estimate  Naive SE  Robust SE       F stat    df
## [1] Intercept       -2.221     0.1407    0.1411           247.78 1 
##     dummy(race)                                             2.11 3 
## [2]    race.2        0.6568    0.2949    0.2957             4.93 1 
## [3]    race.3       -0.4648    0.6131    0.6147             0.57 1 
## [4]    race.4        0.6113    0.7873    0.7894             0.60 1 
##                    Pr(&gt;F)   
## [1] Intercept      &lt; 0.00005
##     dummy(race)      0.0977 
## [2]    race.2        0.0267 
## [3]    race.3        0.4498 
## [4]    race.4        0.4390 
## 
## Transformed Model:
##                    e(Est)    e(95%L)   e(95%H)         F stat    df
## [1] Intercept        0.1085   0.08227    0.1432           247.78 1 
##     dummy(race)                                             2.11 3 
## [2]    race.2        1.929     1.079     3.446              4.93 1 
## [3]    race.3        0.6282    0.1879    2.100              0.57 1 
## [4]    race.4        1.843     0.3912    8.681              0.60 1 
##                    Pr(&gt;F)   
## [1] Intercept      &lt; 0.00005
##     dummy(race)      0.0977 
## [2]    race.2        0.0267 
## [3]    race.3        0.4498 
## [4]    race.4        0.4390 
## 
##  Dummy terms calculated from race, reference = 1 
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 501.59  on 734  degrees of freedom
## Residual deviance: 495.55  on 731  degrees of freedom
## AIC: 503.55
## 
## Number of Fisher Scoring iterations: 5
</code></pre>

<p>First, notice that below the table <code>regress()</code> tells us how the dummy variables were calculated. In this case the reference was 1, corresponding to <code>white</code> in this data set. Next we see the multiple-partial F-test, which is on its own line for <code>dummy(race)</code>. The coefficient estimates are nested beneath this line to indicate that these coefficients all come from the same variable (<code>race</code>) but we have modeled them as three variables.</p>

<h1>User-specified Multiple-partial F-tests</h1>

<p>As we mentioned above, the <em>formula</em> in <code>regress()</code> allows you to specify multiple-partial F-tests. This comes in handy if you want to test a subset of variables all at once in your regression. </p>

<p>For example, say that we are interested in the relationship between atrophy, age, sex, and race. However, we also want to include the sex-age interaction and the sex-race interaction. We also want to model race as dummy variables. Last, we want to determine if all of the variables involved in the sex-age interaction (<code>male</code>, <code>age</code>, and the interaction) should be in the model, and similar for the sex-race interaction. We use the <code>U()</code> function to accomplish this goal.</p>

<pre><code class="r">regress(&quot;mean&quot;, atrophy ~ U(ma = ~male*age) + U(mr = ~male*dummy(race)), data = mri)
</code></pre>

<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ U(ma = ~male * age) + 
##     U(mr = ~male * dummy(race)), data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.682  -8.236  -0.236   7.158  52.546 
## 
## Coefficients:
##                            Estimate  Naive SE  Robust SE    95%L     
## [1]  Intercept              -8.448     8.881     9.005       -26.13  
##      ma                                                              
## [2]    male                 -11.40     12.19     12.88       -36.69  
## [3]    age                   0.5558    0.1193    0.1208       0.3187 
## [4]    male:age              0.2414    0.1632    0.1730     -0.09826 
##      mr                                                              
##        male                 -11.40     12.19     12.88       -36.69  
##        dummy(race)                                                   
## [5]       race.2            -1.003     1.796     1.825       -4.585  
## [6]       race.3             1.713     2.463     2.067       -2.345  
## [7]       race.4             2.070     6.040     8.518       -14.65  
##        male:dummy(race)                                              
## [8]       male:race.2       -2.202     2.560     2.488       -7.086  
## [9]       male:race.3       -2.883     3.664     3.688       -10.12  
## [10]      male:race.4       -7.558     7.415     9.366       -25.95  
##                            95%H         F stat    df Pr(&gt;F)   
## [1]  Intercept               9.231           0.88 1    0.3485 
##      ma                                     34.35 3  &lt; 0.00005
## [2]    male                  13.89           0.78 1    0.3764 
## [3]    age                   0.7929         21.18 1  &lt; 0.00005
## [4]    male:age              0.5811          1.95 1    0.1634 
##      mr                                      1.04 7    0.4038 
##        male                  13.89           0.78 1    0.3764 
##        dummy(race)                           0.40 3    0.7539 
## [5]       race.2             2.579           0.30 1    0.5826 
## [6]       race.3             5.770           0.69 1    0.4076 
## [7]       race.4             18.79           0.06 1    0.8081 
##        male:dummy(race)                      0.61 3    0.6084 
## [8]       male:race.2        2.682           0.78 1    0.3764 
## [9]       male:race.3        4.357           0.61 1    0.4346 
## [10]      male:race.4        10.83           0.65 1    0.4200 
## 
##  Dummy terms calculated from race, reference = 1 
## 
## Residual standard error: 12 on 725 degrees of freedom
## Multiple R-squared:  0.1488, Adjusted R-squared:  0.1382 
## F-statistic: 12.15 on 9 and 725 DF,  p-value: &lt; 2.2e-16
</code></pre>

<p>We have also made use of functionality in <code>U()</code> which allows us to name the groups for the multiple-partial F-tests. Thus we can see that the F-statistic for simultaneously testing whether <code>male</code>, <code>age</code>, and the interaction <code>male:age</code> are equal to zero is 34.35, with the correct degrees of freedom for the test (3) and a small p-value. We would conclude (without adjusting for multiple comparisons) that (some of) these variables should be in the model. On the other hand, we see that the F-statistic for simultaneously testing whether <code>male</code>, <code>race</code>, and the interaction are equal to zero is 1.04. We would conclude (again without adjusting for multiple comparisons) that we cannot reject the null hypothesis that these are all equal to zero.</p>

<p>We also get individual coefficient estimates for each, where we have again nested the estimates within their corresponding groups defined by calls to <code>U()</code>. Note that we have repeated the line for <code>male</code> since it appears in both groups. Other than that, the coefficients table is the same as it would be if we had run the formula <code>atrophy ~ male*age + male*dummy(race)</code>. </p>

</body>

</html>
